---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '28080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
    - 28080:28080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      OLLAMA_API_ENDPOINT: "http://ollama:11434/api/embeddings"
      OLLAMA_MODEL: "herald/dmeta-embedding-zh"
      OLLAMA_GENERATIVE_MODEL: "DeepSeek-R1:14b"
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
...
